#!/bin/bash

# Ground Control
# Version: 1.00
# Description: Ground Control is a simple connection selector.

# load configuration from file if available
file=${HOME}/.ctrlconf
if ! [ -f ${file} ];
then
  echo "Configuration file ~/.ctrlconf missing. Please create the file."
  exit
fi

# to make things easier we are using source
source ${file}

# check for key parameters
if [ -z ${username} ] || [ -z ${hostname} ] \
  || [ -z ${local} ] || [ -z ${remote} ];
then
  echo "Missing username, hostname, or port setting in ${file}"
  exit
fi

# options:
# -l -- from the local network
# -r -- from the remote network
help="You can pass the following options to the command:
  [-l] -- from the local network
  Example: rm_gc -l
  [-r] -- from the remote network
  Example: rm_gc -r
  [-h] -- for help 
  Example: rm_gc -h
"

# accept user options
options=$1

# allows the user to override the IP check 
if [[ "${options//-}" == "h" ]];
then
  printf "${help}"
  exit
elif [[ "${options//-}" == "l" ]];
then
  ssh ${username}@${hostname} -p ${local} ${ssh_key}
  exit
elif [[ "${options//-}" == "r" ]];
then
  ssh ${username}@${hostname} -p ${remote} ${ssh_key}
  exit
fi

# connection decisions

# If we don't pass an option
# the script will try to find out the correct
# setting based on our IP address and the
# settings in .ctrlconf configuration file
ip=$(/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com)

# check if ssh key is set
# this only works if the permissions on the key are correct
! [ -z $key ] && ssh_key="-i ${key}"

if [[ "$ip" == "$office" ]];
then
  ssh ${username}@${hostname} -p ${local} ${ssh_key}
  exit
elif [[ "$ip" != "$office" ]];
then
  ssh ${username}@${hostname} -p ${remote} ${ssh_key}
  exit
else 
  printf "${help}"
  exit
fi
